// <auto-generated />
using System;
using DigitalRegistry.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DigitalRegistry.Migrations
{
    [DbContext(typeof(DigitalRegistryContext))]
    [Migration("20191123030529_tagsCreation")]
    partial class tagsCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DigitalRegistry.Models.Agency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Result2id");

                    b.Property<int?>("Result3id");

                    b.Property<string>("info_url");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.HasIndex("Result2id");

                    b.HasIndex("Result3id");

                    b.ToTable("Agency");
                });

            modelBuilder.Entity("DigitalRegistry.Models.MobileApp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("icon_url");

                    b.Property<string>("language");

                    b.Property<string>("long_description");

                    b.Property<string>("name");

                    b.Property<string>("short_description");

                    b.HasKey("id");

                    b.ToTable("mobileApps");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Result", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("gallery_count");

                    b.Property<string>("info_url");

                    b.Property<int>("mobile_app_count");

                    b.Property<string>("name");

                    b.Property<int>("social_media_count");

                    b.HasKey("id");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Result2", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("created_at");

                    b.Property<string>("icon_url");

                    b.Property<string>("language");

                    b.Property<string>("long_description");

                    b.Property<string>("name");

                    b.Property<string>("short_description");

                    b.Property<DateTime?>("updated_at");

                    b.HasKey("id");

                    b.ToTable("Result2");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Result3", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("account");

                    b.Property<DateTime>("created_at");

                    b.Property<string>("language");

                    b.Property<string>("long_description");

                    b.Property<string>("organization");

                    b.Property<string>("service_display_name");

                    b.Property<string>("service_key");

                    b.Property<string>("service_url");

                    b.Property<string>("short_description");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("id");

                    b.ToTable("Result3");
                });

            modelBuilder.Entity("DigitalRegistry.Models.SocialMedia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("account");

                    b.Property<string>("language");

                    b.Property<string>("long_description");

                    b.Property<string>("organization");

                    b.Property<string>("service_display_name");

                    b.Property<string>("service_key");

                    b.Property<string>("service_url");

                    b.Property<string>("short_description");

                    b.HasKey("id");

                    b.ToTable("socialMedias");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Tag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Result2id");

                    b.Property<int?>("Result3id");

                    b.Property<string>("tag_text");

                    b.HasKey("id");

                    b.HasIndex("Result2id");

                    b.HasIndex("Result3id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Tags", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("gallery_count");

                    b.Property<int>("mobile_app_count");

                    b.Property<int>("social_media_count");

                    b.Property<string>("tag_text");

                    b.Property<string>("tag_type");

                    b.HasKey("id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Version", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Result2id");

                    b.Property<string>("average_rating");

                    b.Property<string>("device");

                    b.Property<int?>("number_of_ratings");

                    b.Property<string>("platform");

                    b.Property<DateTime?>("publish_date");

                    b.Property<string>("screenshot");

                    b.Property<string>("store_url");

                    b.Property<string>("version_number");

                    b.HasKey("id");

                    b.HasIndex("Result2id");

                    b.ToTable("Version");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Agency", b =>
                {
                    b.HasOne("DigitalRegistry.Models.Result2")
                        .WithMany("agencies")
                        .HasForeignKey("Result2id");

                    b.HasOne("DigitalRegistry.Models.Result3")
                        .WithMany("agencies")
                        .HasForeignKey("Result3id");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Tag", b =>
                {
                    b.HasOne("DigitalRegistry.Models.Result2")
                        .WithMany("Tags")
                        .HasForeignKey("Result2id");

                    b.HasOne("DigitalRegistry.Models.Result3")
                        .WithMany("tags")
                        .HasForeignKey("Result3id");
                });

            modelBuilder.Entity("DigitalRegistry.Models.Version", b =>
                {
                    b.HasOne("DigitalRegistry.Models.Result2")
                        .WithMany("versions")
                        .HasForeignKey("Result2id");
                });
#pragma warning restore 612, 618
        }
    }
}
